package factory

import (
	"github.com/mechanical-lich/ml-rogue-lib/pkg/rlcomponents"
	"github.com/mechanical-lich/mlge/ecs"
	"github.com/mechanical-lich/spaceplant/internal/component"
)

// registerComponents registers all component constructors with the jsonFactory.
func registerComponents() {
	jsonFactory.RegisterComponent("DescriptionComponent", func() ecs.Component { return &rlcomponents.DescriptionComponent{} })
	jsonFactory.RegisterComponent("AppearanceComponent", func() ecs.Component { return &component.AppearanceComponent{} })
	jsonFactory.RegisterComponent("SolidComponent", func() ecs.Component { return &rlcomponents.SolidComponent{} })
	jsonFactory.RegisterComponent("EnergyComponent", func() ecs.Component { return &rlcomponents.EnergyComponent{} })
	jsonFactory.RegisterComponent("InventoryComponent", func() ecs.Component { return &rlcomponents.InventoryComponent{} })
	jsonFactory.RegisterComponent("StatsComponent", func() ecs.Component { return &component.StatsComponent{} })
	jsonFactory.RegisterComponent("InanimateComponent", func() ecs.Component { return &rlcomponents.InanimateComponent{} })
	jsonFactory.RegisterComponent("PositionComponent", func() ecs.Component { return &rlcomponents.PositionComponent{} })
	jsonFactory.RegisterComponent("DirectionComponent", func() ecs.Component { return &rlcomponents.DirectionComponent{} })
	jsonFactory.RegisterComponent("WanderAIComponent", func() ecs.Component { return &rlcomponents.WanderAIComponent{} })
	jsonFactory.RegisterComponent("HostileAIComponent", func() ecs.Component { return &rlcomponents.HostileAIComponent{} })
	jsonFactory.RegisterComponent("FoodComponent", func() ecs.Component { return &rlcomponents.FoodComponent{} })
	jsonFactory.RegisterComponent("DamageConditionComponent", func() ecs.Component { return &rlcomponents.DamageConditionComponent{} })
	jsonFactory.RegisterComponent("HasteComponent", func() ecs.Component { return &rlcomponents.HasteComponent{} })
	jsonFactory.RegisterComponent("SlowedComponent", func() ecs.Component { return &rlcomponents.SlowedComponent{} })
	jsonFactory.RegisterComponent("DefensiveAIComponent", func() ecs.Component { return &rlcomponents.DefensiveAIComponent{} })
	jsonFactory.RegisterComponent("NeverSleepComponent", func() ecs.Component { return &rlcomponents.NeverSleepComponent{} })
	jsonFactory.RegisterComponent("NocturnalComponent", func() ecs.Component { return &rlcomponents.NocturnalComponent{} })
	jsonFactory.RegisterComponent("MassiveComponent", func() ecs.Component { return &component.MassiveComponent{} })
	jsonFactory.RegisterComponent("InteractionComponent", func() ecs.Component { return &rlcomponents.InteractionComponent{} })
	jsonFactory.RegisterComponent("DoorComponent", func() ecs.Component { return &rlcomponents.DoorComponent{} })
	jsonFactory.RegisterComponent("ItemComponent", func() ecs.Component { return &rlcomponents.ItemComponent{} })
	jsonFactory.RegisterComponent("ArmorComponent", func() ecs.Component { return &rlcomponents.ArmorComponent{} })
	jsonFactory.RegisterComponent("WeaponComponent", func() ecs.Component { return &component.WeaponComponent{} })
	jsonFactory.RegisterComponent("MyTurnComponent", func() ecs.Component { return &rlcomponents.MyTurnComponent{} })
	jsonFactory.RegisterComponent("DeadComponent", func() ecs.Component { return &rlcomponents.DeadComponent{} })
	jsonFactory.RegisterComponent("AlertedComponent", func() ecs.Component { return &rlcomponents.AlertedComponent{} })
	jsonFactory.RegisterComponent("PlayerComponent", func() ecs.Component { return &component.PlayerComponent{} })
	jsonFactory.RegisterComponent("AttackComponent", func() ecs.Component { return &component.AttackComponent{} })
	jsonFactory.RegisterComponent("LightComponent", func() ecs.Component { return &component.LightComponent{} })
	jsonFactory.RegisterComponent("AsciiAppearanceComponent", func() ecs.Component { return &rlcomponents.AsciiAppearanceComponent{} })
	jsonFactory.RegisterComponent("KeyComponent", func() ecs.Component { return &rlcomponents.KeyComponent{} })
	jsonFactory.RegisterComponent("TurnTakenComponent", func() ecs.Component { return &rlcomponents.TurnTakenComponent{} })
	jsonFactory.RegisterComponent("SizeComponent", func() ecs.Component { return &rlcomponents.SizeComponent{} })
	jsonFactory.RegisterComponent("BodyComponent", func() ecs.Component { return &rlcomponents.BodyComponent{} })
	jsonFactory.RegisterComponent("BodyInventoryComponent", func() ecs.Component { return &rlcomponents.BodyInventoryComponent{} })
	jsonFactory.RegisterComponent("DropsComponent", func() ecs.Component { return &rlcomponents.DropsComponent{} })
	jsonFactory.RegisterComponent("SkillComponent", func() ecs.Component { return &component.SkillComponent{} })
	jsonFactory.RegisterComponent("ItemSkillsComponent", func() ecs.Component { return &component.ItemSkillsComponent{} })
	jsonFactory.RegisterComponent("ClassComponent", func() ecs.Component { return &component.ClassComponent{} })
	jsonFactory.RegisterComponent("BackgroundComponent", func() ecs.Component { return &component.BackgroundComponent{} })
	jsonFactory.RegisterComponent("AdvancedAIComponent", func() ecs.Component { return &component.AdvancedAIComponent{} })
	jsonFactory.RegisterComponent("LayeredAppearanceComponent", func() ecs.Component { return &component.LayeredAppearanceComponent{} })
	jsonFactory.RegisterComponent("WearableAppearanceComponent", func() ecs.Component { return &component.WearableAppearanceComponent{} })
	jsonFactory.RegisterComponent("ActiveConditionsComponent", func() ecs.Component { return &rlcomponents.ActiveConditionsComponent{} })
	jsonFactory.RegisterComponent("HitLocationComponent", func() ecs.Component { return &component.HitLocationComponent{} })
	jsonFactory.RegisterComponent("AmmoComponent", func() ecs.Component { return &component.AmmoComponent{} })
	jsonFactory.RegisterComponent("ScriptComponent", func() ecs.Component { return &component.ScriptComponent{} })
}
